language: node_js
node_js:
  - "4.4.7"
sudo: false
before_script:
  - psql -c 'create database test;' -U postgres
before_install:
  - pip install --user codecov
  - $CXX --version
after_success:
  - codecov --file coverage/lcov.info --disable search
env:
  global:
    - CXX=g++-4.8
    - JWT_SECRET="EverythingIsAwesome!"
    - DATABASE_URL=postgres://postgres:@localhost/test
addons:
  postgresql: "9.4"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
