version: '2'
services:
    postgres:
        image: postgres
    redis:
        image: redis
    app:
        image: node
        volumes:
          - .:/app
        environment:
          - PORT=3000
        ports:
          - 3000:3000
        command: bash -c "cd /app && ./node_modules/nodemon/bin/nodemon.js server.js"
