name: dwyl_todo
description: Clear your mind. Organise your life. Ignore distractions. Focus on what matters.
publish_to: 'none'
version: 0.1.0
homepage: https://github.com/dwyl/app
repository: https://github.com/dwyl/app
issue_tracker: https://github.com/dwyl/app/issues

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc_test: ^9.1.3
  equatable: ^2.0.5
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
