name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      # Installing Flutter because it's easier to generate .lcov files for test coverage
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
       
      - name: Flutter analyze
        run: flutter analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run tests
        run: flutter test --coverage

      - uses: codecov/codecov-action@v2
        with:
          files: coverage/lcov.info
          verbose: true # optional (default = false)


  # Continuous Deployment to Fly.io
  # https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/
  flutter_deploy:
    name: Deploy Flutter app
    runs-on: ubuntu-latest

    needs: [build]
    # https://stackoverflow.com/questions/58139406/only-run-job-on-specific-branch-with-github-actions
    # if: github.ref == 'refs/heads/main'
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create release build
        # github.com/dwyl/app/issues/315#issuecomment-1443747737
        run: flutter build web --release --web-renderer html
        
      - name: Run post-build script to download files concurrently
        run: | 
          chmod +x ./build_tools/patch_web.sh
          sh ./build_tools/patch_web.sh --ignore-whitespace

      - uses: superfly/flyctl-actions@1.1
        with:
          args: "deploy"