name: Deploy Android (Google Play Store)
on:
  # Only trigger, when the "build" workflow succeeded (only works in the Master Branch)
  workflow_run:
    workflows: ["Build & Test"]
    types:
      - completed

  # Only trigger, when pushing into the `main` branch
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Needed to base64 decode the upload keystore
      - name: ⚙️ Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
        id: java

      # Needed to run Flutter-based commands
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.5"
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get
